### ISSUE TITLE
[Checklist] Providing Xline client Rust SDK

### ISSUE THREAD

**Issue by bsbds** [xline-kv/Xline#369]
## Background:
As discussed in #273, we need to provide a Xline specific client SDK for Rust. While some progress has been made on the client, further refinement is required before it can be released as a standalone SDK.

## Checklist
-  Implement APIs
    - [ ] Implement all APIs supported by Xline, maintain the progress in [README](https://github.com/xline-kv/Xline/blob/master/xline-client/README.md)
-  Update README
    - [ ] The README should include introduction sections to users, and maintain a section to track the compatible version of Xline
-  Add examples to the crate
   - [ ] For each API client, there should be an example under `xline-client/examples`
- Update documents
   - [ ] Add detailed description for each method, struct and enum
   - [ ] Add examples to API methods
- Release
   - [ ] Publish `xline-client` as a standalone SDK on crates.io
